question_database = [
    ("What is the fundamental unit of information in binary code?", "Bit"),
    ("What is a database management system developed by Microsoft?", "SQL"),
    ("What is a popular cloud computing platform developed by Amazon?", "AWS"),
    ("What is the process of finding and fixing errors in software?", "Debugging"),
    ("What is the term for the process of transforming plaintext into unreadable ciphertext to secure data?", "Encryption"),
    ("What is a program used for managing and organizing data?", "Database"),
    ("What is a set of rules for data transmission?", "Protocol"),
    ("What is a program that performs a specific task?", "Application"),
    ("What is a set of instructions that a computer follows to perform a specific task?", "Algorithm"),
    ("What is the code that represents characters in a computer?", "ASCII"),
    ("What is a program that monitors and controls system activities?", "Firewall"),
    ("What is a program that protects a computer from malware?", "Antivirus"),
    ("What is a digital signature used for in computer security?", "Authentication"),
    ("What is the process of hiding data within other data to protect it from unauthorized access?", "Steganography"),
    ("What is a sequence of instructions for a computer?", "Program"),
    ("What is a programming language designed for numerical and scientific computing?", "MATLAB"),
    ("What is a technology for sharing data between devices via short-range radio waves?", "Bluetooth"),
    ("What is a system of naming files and directories on a computer?", "Filesystem"),
    ("What is a technology for wireless data communication?", "Wi-Fi"),
    ("What is a network device that forwards data packets between different networks?", "Router"),
    ("What is a device that converts digital signals to analog and vice versa?", "Modem"),
    ("What is the term for the process of converting high-level programming code into machine code?", "Compilation"),
    ("What is the term for a programming construct that allows a function to call itself?", "Recursion"),
    ("What is the name of the data structure that enforces a last-in, first-out (LIFO) order for elements?", "Stack"),
    ("What is a graphical representation of data trends?", "Chart"),
    ("What is the smallest prime number?", "Two"),
    ("What is the main greenhouse gas responsible for global warming?", "Carbon"),
    ("What is the name of India's first indigenously developed COVID-19 vaccine?", "Covaxin"),
    ("Which Indian city was chosen to host the 2022 G20 summit?", "Delhi"),
    ("Which city was chosen as the host for the 2024 Summer Olympics?", "Paris"),
    ("Which Indian city is known as the 'Silicon valley of India'?", "Bengaluru"),
    ("Which gas makes up the majority of Earth's atmosphere?", "Nitrogen"),
    ("What is the tallest mountain in the world?", "Everest"),
    ("What is the largest desert in the world?", "Sahara"),
    ("Which river is the longest in the world?", "Nile"),
    ("What is the largest ocean on Earth?", "Pacific"),
    ("What is the largest continent?", "Asia"),
    ("What is the largest planet in our solar system?", "Jupiter"),
    ("Which planet is often referred to as the 'Red Planet'?", "Mars"),
    ("What is the smallest planet in our solar system?", "Mercury"),
    ("In physics, what is the fundamental unit of electric charge?", "Electron"),
    ("What is the chemical symbol for silver?", "Ag"),
    ("In which state is the famous Ajanta Caves located?", "Maharashtra"),
    ("In which year did India become a republic and adopt its Constitution?", "1950"),
    ("What is the currency of India?", "Rupee"),
    ("What is the name of India's space agency?", "ISRO"),
    ("What is the largest river in India?", "Ganga"),
    ("What is the Indian space agency's lunar mission known as?", "Chandrayaan"),
    ("What is the value of π (pi) to two decimal places?", "3.14"),
    ("What is the term for a polygon with eight sides?", "Octagon"),
    ("What is the capital of France?", "Paris"),
    ("Which planet is known as the Red Planet?", "Mars"),
    ("What is 7 x 8?", "56"),
    ("Who wrote 'Romeo and Juliet'?", "Shakespeare")
]